# Generated by Django 5.2.6 on 2025-09-12 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0002_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='management_desk',
            old_name='positin',
            new_name='position',
        ),
    ]
