# Generated by Django 5.1.4 on 2025-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0003_rename_positin_management_desk_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator_desk',
            old_name='positin',
            new_name='position',
        ),
    ]
