# Generated by Django 5.1.4 on 2025-09-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0005_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notice Title')),
                ('description', models.TextField(verbose_name='Notice Description')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Event Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
