# Generated by Django 5.1.4 on 2025-09-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0006_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='courses',
            name='about',
            field=models.TextField(default='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.CharField(default='1 year (Full Time)', max_length=200),
            preserve_default=False,
        ),
    ]
