# Generated by Django 5.1.4 on 2025-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0007_alter_courses_options_courses_about_courses_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal_desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='principal_desk_images/')),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
