# Generated by Django 5.2 on 2026-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0008_principal_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtdayGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artday_gallery_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Co_curricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='co_curricular_images/')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
