# Generated by Django 5.2 on 2026-05-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0009_artdaygallery_co_curricular_home_image2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Co_curricular',
            new_name='Co_curricularGallery',
        ),
    ]
