# Generated by Django 5.2 on 2026-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0010_rename_co_curricular_co_curriculargallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpComingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('date', models.DateField(verbose_name='Event Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Event Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Events',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
