# Generated by Django 5.2 on 2026-05-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0011_upcomingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
