# Generated by Django 5.2 on 2026-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0012_home_image3_home_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='home',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
    ]
