# Generated by Django 5.2 on 2026-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0013_home_image5_home_image6_home_image7'),
    ]

    operations = [
        migrations.AddField(
            model_name='management_desk',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
