# Generated by Django 5.2 on 2026-06-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0014_management_desk_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(blank=True, choices=[('Law Faculty', 'Law Faculty'), ('Non-Law Faculty', 'Non-Law Faculty')], max_length=20, null=True),
        ),
    ]
