# Generated by Django 5.2 on 2026-06-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilahia_app', '0016_ourachivements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourachivements',
            options={'verbose_name': 'Our Achievements', 'verbose_name_plural': 'Our Achievements'},
        ),
        migrations.AddField(
            model_name='management_desk',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
